In [1]:
# Import Dependencies
import pandas as pd

In [2]:
# Import the games file
games_file = "./Resources/games.csv"

# Load games data into a dataframe
games_df = pd.read_csv(games_file)

games_df.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,25.0,40.0,1610612748,87.0,0.400,0.741,0.280,14.0,41.0,1
1,2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,...,13.0,27.0,1610612759,107.0,0.571,0.720,0.429,25.0,44.0,0
2,2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,...,17.0,26.0,1610612759,111.0,0.594,0.813,0.450,21.0,29.0,0
3,2014-06-08,41300402,Final,1610612759,1610612748,2013,1610612759,96.0,0.439,0.600,...,26.0,37.0,1610612748,98.0,0.529,0.762,0.421,16.0,38.0,0
4,2014-06-05,41300401,Final,1610612759,1610612748,2013,1610612759,110.0,0.588,0.773,...,30.0,39.0,1610612748,95.0,0.474,0.818,0.414,16.0,29.0,1

In [3]:
# Count the data
games_df.count()

GAME_DATE_EST       22594
GAME_ID             22594
GAME_STATUS_TEXT    22594
HOME_TEAM_ID        22594
VISITOR_TEAM_ID     22594
SEASON              22594
TEAM_ID_home        22594
PTS_home            22495
FG_PCT_home         22495
FT_PCT_home         22495
FG3_PCT_home        22495
AST_home            22495
REB_home            22495
TEAM_ID_away        22594
PTS_away            22495
FG_PCT_away         22495
FT_PCT_away         22495
FG3_PCT_away        22495
AST_away            22495
REB_away            22495
HOME_TEAM_WINS      22594
dtype: int64

In [4]:
# Drop NA values
games_df = games_df.dropna(how='any')
games_df.count()

GAME_DATE_EST       22495
GAME_ID             22495
GAME_STATUS_TEXT    22495
HOME_TEAM_ID        22495
VISITOR_TEAM_ID     22495
SEASON              22495
TEAM_ID_home        22495
PTS_home            22495
FG_PCT_home         22495
FT_PCT_home         22495
FG3_PCT_home        22495
AST_home            22495
REB_home            22495
TEAM_ID_away        22495
PTS_away            22495
FG_PCT_away         22495
FT_PCT_away         22495
FG3_PCT_away        22495
AST_away            22495
REB_away            22495
HOME_TEAM_WINS      22495
dtype: int64

In [5]:
# Check for duplicates
duplicates = games_df[games_df.duplicated()]
duplicates

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
18758,2017-03-02,21600908,Final,1610612757,1610612760,2016,1610612757,114.0,0.494,0.743,...,19.0,45.0,1610612760,109.0,0.395,0.938,0.379,11.0,40.0,1

In [6]:
# Drop duplicates
games_df.drop_duplicates(keep='first', inplace=True)
games_df.count()

GAME_DATE_EST       22494
GAME_ID             22494
GAME_STATUS_TEXT    22494
HOME_TEAM_ID        22494
VISITOR_TEAM_ID     22494
SEASON              22494
TEAM_ID_home        22494
PTS_home            22494
FG_PCT_home         22494
FT_PCT_home         22494
FG3_PCT_home        22494
AST_home            22494
REB_home            22494
TEAM_ID_away        22494
PTS_away            22494
FG_PCT_away         22494
FT_PCT_away         22494
FG3_PCT_away        22494
AST_away            22494
REB_away            22494
HOME_TEAM_WINS      22494
dtype: int64

In [7]:
# Now check the game details file
# Create a variable to hold the file path
game_details = './Resources/games_details.csv'

# Import data into a dataframe
gd_df = pd.read_csv(game_details)

# Preview the data
gd_df.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,MIN,FGM,FGA,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,40800405,1610612747,LAL,Los Angeles,2772,Trevor Ariza,F,41:29:00,5.0,12.0,...,1.0,4.0,5.0,1.0,2.0,0.0,3.0,3.0,15.0,12.0
1,40800405,1610612747,LAL,Los Angeles,2200,Pau Gasol,F,42:09:00,6.0,9.0,...,4.0,11.0,15.0,3.0,0.0,4.0,1.0,2.0,14.0,15.0
2,40800405,1610612747,LAL,Los Angeles,101115,Andrew Bynum,C,16:54,3.0,11.0,...,4.0,1.0,5.0,0.0,1.0,0.0,1.0,5.0,6.0,-6.0
3,40800405,1610612747,LAL,Los Angeles,977,Kobe Bryant,G,43:18:00,10.0,23.0,...,0.0,6.0,6.0,5.0,2.0,4.0,1.0,2.0,30.0,14.0
4,40800405,1610612747,LAL,Los Angeles,965,Derek Fisher,G,31:59:00,4.0,7.0,...,0.0,4.0,4.0,2.0,0.0,0.0,1.0,4.0,13.0,16.0

In [8]:
# Count the data
gd_df.count()

GAME_ID              561733
TEAM_ID              561733
TEAM_ABBREVIATION    561733
TEAM_CITY            561733
PLAYER_ID            561733
PLAYER_NAME          561733
START_POSITION       215354
MIN                  471808
FGM                  471808
FGA                  471808
FG_PCT               471808
FG3M                 471808
FG3A                 471808
FG3_PCT              471808
FTM                  471808
FTA                  471808
FT_PCT               471808
OREB                 471808
DREB                 471808
REB                  471808
AST                  471808
STL                  471808
BLK                  471808
TO                   471808
PF                   471808
PTS                  471808
PLUS_MINUS           448147
dtype: int64

In [9]:
# Drop NA values
gd_df = gd_df.dropna(how='any')

# Re-count the data
gd_df.count()

GAME_ID              215354
TEAM_ID              215354
TEAM_ABBREVIATION    215354
TEAM_CITY            215354
PLAYER_ID            215354
PLAYER_NAME          215354
START_POSITION       215354
MIN                  215354
FGM                  215354
FGA                  215354
FG_PCT               215354
FG3M                 215354
FG3A                 215354
FG3_PCT              215354
FTM                  215354
FTA                  215354
FT_PCT               215354
OREB                 215354
DREB                 215354
REB                  215354
AST                  215354
STL                  215354
BLK                  215354
TO                   215354
PF                   215354
PTS                  215354
PLUS_MINUS           215354
dtype: int64

In [10]:
# Now merge the data
merge = pd.merge(games_df, gd_df, on='GAME_ID', how='inner')

# Preview the data
merge.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,1.0,9.0,10.0,5.0,0.0,2.0,1.0,1.0,31.0,-16.0
1,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0,8.0
2,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,7.0,7.0,2.0,1.0,0.0,0.0,2.0,13.0,-20.0
3,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,3.0,3.0,1.0,0.0,0.0,3.0,3.0,11.0,-10.0
4,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,1.0,4.0,5.0,2.0,1.0,0.0,4.0,2.0,5.0,-18.0

In [11]:
# Count the data
merge.count()

GAME_DATE_EST        215354
GAME_ID              215354
GAME_STATUS_TEXT     215354
HOME_TEAM_ID         215354
VISITOR_TEAM_ID      215354
SEASON               215354
TEAM_ID_home         215354
PTS_home             215354
FG_PCT_home          215354
FT_PCT_home          215354
FG3_PCT_home         215354
AST_home             215354
REB_home             215354
TEAM_ID_away         215354
PTS_away             215354
FG_PCT_away          215354
FT_PCT_away          215354
FG3_PCT_away         215354
AST_away             215354
REB_away             215354
HOME_TEAM_WINS       215354
TEAM_ID              215354
TEAM_ABBREVIATION    215354
TEAM_CITY            215354
PLAYER_ID            215354
PLAYER_NAME          215354
START_POSITION       215354
MIN                  215354
FGM                  215354
FGA                  215354
FG_PCT               215354
FG3M                 215354
FG3A                 215354
FG3_PCT              215354
FTM                  215354
FTA                  215354
FT_PCT               215354
OREB                 215354
DREB                 215354
REB                  215354
AST                  215354
STL                  215354
BLK                  215354
TO                   215354
PF                   215354
PTS                  215354
PLUS_MINUS           215354
dtype: int64

In [12]:
# Preview the dataframe 
merge.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,1.0,9.0,10.0,5.0,0.0,2.0,1.0,1.0,31.0,-16.0
1,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0,8.0
2,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,7.0,7.0,2.0,1.0,0.0,0.0,2.0,13.0,-20.0
3,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,3.0,3.0,1.0,0.0,0.0,3.0,3.0,11.0,-10.0
4,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,1.0,4.0,5.0,2.0,1.0,0.0,4.0,2.0,5.0,-18.0

In [13]:
# Check the end of the dataframe
merge.tail()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
215349,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,2.0,1.0,3.0,1.0,2.0,0.0,0.0,0.0,4.0,-16.0
215350,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,0.0,2.0,2.0,1.0,1.0,0.0,0.0,2.0,2.0,-8.0
215351,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,1.0,5.0,6.0,2.0,1.0,0.0,4.0,2.0,9.0,-10.0
215352,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,0.0,2.0,2.0,3.0,0.0,0.0,1.0,1.0,6.0,-11.0
215353,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,...,0.0,3.0,3.0,2.0,1.0,0.0,2.0,1.0,2.0,-6.0

In [14]:
# Set the Game Date as the index
merge = merge.set_index("GAME_DATE_EST")

# Preview the data
merge.head()

,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
GAME_DATE_EST,,,,,,,,,,,,,,,,,,,,,
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,1.0,9.0,10.0,5.0,0.0,2.0,1.0,1.0,31.0,-16.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0,8.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,0.0,7.0,7.0,2.0,1.0,0.0,0.0,2.0,13.0,-20.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,0.0,3.0,3.0,1.0,0.0,0.0,3.0,3.0,11.0,-10.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,1.0,4.0,5.0,2.0,1.0,0.0,4.0,2.0,5.0,-18.0

In [15]:
# Now look again at the tail
merge.tail()

,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
GAME_DATE_EST,,,,,,,,,,,,,,,,,,,,,
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,2.0,1.0,3.0,1.0,2.0,0.0,0.0,0.0,4.0,-16.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,2.0,2.0,1.0,1.0,0.0,0.0,2.0,2.0,-8.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,1.0,5.0,6.0,2.0,1.0,0.0,4.0,2.0,9.0,-10.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,2.0,2.0,3.0,0.0,0.0,1.0,1.0,6.0,-11.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,3.0,3.0,2.0,1.0,0.0,2.0,1.0,2.0,-6.0

In [16]:
merge

,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
GAME_DATE_EST,,,,,,,,,,,,,,,,,,,,,
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,1.0,9.0,10.0,5.0,0.0,2.0,1.0,1.0,31.0,-16.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0,8.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,0.0,7.0,7.0,2.0,1.0,0.0,0.0,2.0,13.0,-20.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,0.0,3.0,3.0,1.0,0.0,0.0,3.0,3.0,11.0,-10.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,1.0,4.0,5.0,2.0,1.0,0.0,4.0,2.0,5.0,-18.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,2.0,8.0,10.0,2.0,1.0,1.0,3.0,6.0,22.0,15.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,2.0,6.0,8.0,2.0,0.0,2.0,0.0,3.0,14.0,5.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,1.0,8.0,9.0,6.0,1.0,0.0,2.0,1.0,5.0,14.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,0.0,2.0,2.0,2.0,2.0,0.0,1.0,0.0,0.0,-4.0
2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,2.0,16.0,1.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,5.0,9.0,14.0,3.0,3.0,3.0,1.0,3.0,20.0,23.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,1.0,10.0,11.0,2.0,2.0,1.0,0.0,3.0,10.0,21.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,3.0,6.0,9.0,9.0,1.0,0.0,2.0,0.0,8.0,15.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,1.0,2.0,3.0,0.0,0.0,0.0,2.0,5.0,9.0,-7.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,0.0,0.0,0.0,2.0,0.0,0.0,4.0,1.0,19.0,16.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,0.0,8.0,8.0,2.0,0.0,0.0,3.0,0.0,28.0,-21.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,2.0,-17.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,0.0,4.0,4.0,0.0,2.0,0.0,2.0,2.0,12.0,-15.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,0.0,2.0,2.0,4.0,4.0,0.0,3.0,4.0,10.0,-9.0
2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,...,0.0,0.0,0.0,5.0,1.0,0.0,1.0,3.0,4.0,-14.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,1.0,3.0,4.0,2.0,2.0,2.0,1.0,4.0,29.0,19.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,2.0,4.0,6.0,2.0,0.0,0.0,4.0,2.0,14.0,8.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,0.0,5.0,5.0,3.0,1.0,1.0,2.0,3.0,9.0,20.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,0.0,1.0,1.0,3.0,5.0,1.0,2.0,4.0,15.0,14.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,0.0,1.0,1.0,4.0,2.0,0.0,1.0,4.0,15.0,12.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,1.0,4.0,5.0,7.0,5.0,0.0,7.0,5.0,22.0,-21.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,0.0,4.0,4.0,0.0,0.0,0.0,0.0,3.0,14.0,-10.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,0.0,3.0,3.0,0.0,0.0,0.0,0.0,4.0,9.0,-18.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,1.0,3.0,4.0,2.0,2.0,0.0,5.0,2.0,22.0,-9.0
2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,...,0.0,2.0,2.0,4.0,0.0,0.0,3.0,4.0,2.0,-2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,10.0,-5.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,1.0,0.0,1.0,0.0,0.0,2.0,2.0,1.0,6.0,4.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,1.0,2.0,3.0,1.0,0.0,0.0,1.0,2.0,13.0,-2.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,0.0,1.0,1.0,2.0,0.0,1.0,1.0,3.0,1.0,-5.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,0.0,2.0,2.0,6.0,1.0,0.0,3.0,2.0,14.0,1.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,0.0,2.0,2.0,1.0,2.0,0.0,2.0,3.0,9.0,5.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,1.0,3.0,4.0,3.0,1.0,0.0,0.0,3.0,6.0,4.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,4.0,7.0,11.0,1.0,0.0,0.0,1.0,4.0,10.0,6.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,0.0,2.0,2.0,5.0,0.0,0.0,3.0,3.0,13.0,7.0
2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,...,0.0,1.0,1.0,5.0,0.0,0.0,2.0,2.0,11.0,3.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,0.0,0.0,0.0,3.0,1.0,2.0,0.0,3.0,9.0,9.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,2.0,5.0,7.0,1.0,0.0,0.0,5.0,1.0,7.0,-4.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,2.0,4.0,6.0,0.0,2.0,1.0,5.0,5.0,13.0,6.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,0.0,2.0,2.0,0.0,1.0,0.0,1.0,1.0,9.0,-1.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,2.0,2.0,4.0,6.0,0.0,0.0,1.0,5.0,13.0,3.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,0.0,1.0,1.0,0.0,2.0,0.0,3.0,2.0,11.0,-12.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,2.0,3.0,5.0,2.0,2.0,0.0,2.0,3.0,0.0,7.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,0.0,4.0,4.0,1.0,0.0,1.0,2.0,2.0,12.0,2.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,2.0,0.0,2.0,1.0,1.0,0.0,1.0,1.0,21.0,2.0
2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,...,0.0,3.0,3.0,3.0,0.0,0.0,0.0,2.0,5.0,3.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,3.0,3.0,2.0,1.0,0.0,1.0,3.0,8.0,9.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,1.0,3.0,4.0,0.0,0.0,3.0,1.0,0.0,5.0,0.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,3.0,3.0,1.0,0.0,1.0,1.0,2.0,2.0,3.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,4.0,4.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,4.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,2.0,1.0,3.0,1.0,2.0,0.0,0.0,0.0,4.0,-16.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,2.0,2.0,1.0,1.0,0.0,0.0,2.0,2.0,-8.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,1.0,5.0,6.0,2.0,1.0,0.0,4.0,2.0,9.0,-10.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,2.0,2.0,3.0,0.0,0.0,1.0,1.0,6.0,-11.0
2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,...,0.0,3.0,3.0,2.0,1.0,0.0,2.0,1.0,2.0,-6.0

In [17]:
# Reset the index
merge = merge.reset_index()

# Preview the data
merge.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,1.0,9.0,10.0,5.0,0.0,2.0,1.0,1.0,31.0,-16.0
1,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,2.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0,8.0
2,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,7.0,7.0,2.0,1.0,0.0,0.0,2.0,13.0,-20.0
3,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,0.0,3.0,3.0,1.0,0.0,0.0,3.0,3.0,11.0,-10.0
4,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,...,1.0,4.0,5.0,2.0,1.0,0.0,4.0,2.0,5.0,-18.0

In [18]:
merge["SEASON"].unique()

array([2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003,
       2019, 2018, 2017, 2016, 2015, 2014], dtype=int64)

In [19]:
# Sort the dataframe by season
merge.sort_values(by=['SEASON'], inplace=True)

# Preview the data
merge.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
132097,2004-03-15,20300964,Final,1610612745,1610612756,2003,1610612745,97.0,0.393,0.720,...,2.0,6.0,8.0,2.0,2.0,3.0,1.0,2.0,29.0,2.0
133267,2004-02-28,20300852,Final,1610612741,1610612744,2003,1610612741,87.0,0.390,0.576,...,3.0,9.0,12.0,1.0,0.0,3.0,1.0,6.0,16.0,0.0
133266,2004-02-28,20300852,Final,1610612741,1610612744,2003,1610612741,87.0,0.390,0.576,...,5.0,9.0,14.0,3.0,2.0,0.0,2.0,4.0,14.0,-13.0
133265,2004-02-28,20300852,Final,1610612741,1610612744,2003,1610612741,87.0,0.390,0.576,...,1.0,2.0,3.0,3.0,1.0,1.0,1.0,3.0,7.0,-12.0
133264,2004-02-28,20300853,Final,1610612742,1610612757,2003,1610612742,111.0,0.517,0.889,...,0.0,3.0,3.0,11.0,0.0,0.0,1.0,2.0,22.0,18.0